version: '3.4'

services:

  hosting:
    build:
      dockerfile: Dockerfile
      context: ./ngrok
    hostname: ngrok
    network_mode: host
    command: ngrok http -log=stdout 8080

    


  main:
    build:
      dockerfile: ./PHP/Dockerfile
      context: .
    hostname: php
    ports:
      - 8080:8080
    command: php -S 0.0.0.0:8080
