version: '3.4'

services:

  hosting:
    build:
      dockerfile: Dockerfile
      context: ./ngrok
    hostname: ngrok
    ports:
      - 4040:4040
    environment:
      - DOMAIN=squad_web
      - PORT=433
    depends_on:
      - main
    command: ngrok http -log=stdout 8080

    


  main:
    build:
      dockerfile: ./PHP/Dockerfile
      context: .
    ports:
      - 8080:8080
    hostname: php      
    command: php -S localhost:8080
